In [2]:
import numpy as np
import pandas as pd

In [3]:
value = [1, 2, 3, 4, 5, 6, 7, 8,10]


In [4]:
grid = np.array([[value[0], value[1], value[2]], [value[3], value[4], value[5]], [value[6],value[7],value[8]]])
print(grid)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]


Best way of doing this: 


In [5]:
grid = np.array(value).reshape((3,3))
print(grid)

print(np.mean(grid, axis =1))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]
[2.         5.         8.33333333]


In [6]:
df = pd.read_csv('./Demographic-Data-Analyzer/adult.data.csv')
df.head()

age         workclass  fnlwgt  education  education-num  \
0   39         State-gov   77516  Bachelors             13   
1   50  Self-emp-not-inc   83311  Bachelors             13   
2   38           Private  215646    HS-grad              9   
3   53           Private  234721       11th              7   
4   28           Private  338409  Bachelors             13   

       marital-status         occupation   relationship   race     sex  \
0       Never-married       Adm-clerical  Not-in-family  White    Male   
1  Married-civ-spouse    Exec-managerial        Husband  White    Male   
2            Divorced  Handlers-cleaners  Not-in-family  White    Male   
3  Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4  Married-civ-spouse     Prof-specialty           Wife  Black  Female   

   capital-gain  capital-loss  hours-per-week native-country salary  
0          2174             0              40  United-States  <=50K  
1             0             0              13  United-States  <=50K  
2             0             0              40  United-States  <=50K  
3             0             0              40  United-States  <=50K  
4             0             0              40           Cuba  <=50K

In [37]:
race_count = pd.Series(df['race'].value_counts())
race_count

White                 27816
Black                  3124
Asian-Pac-Islander     1039
Amer-Indian-Eskimo      311
Other                   271
Name: race, dtype: int64

In [8]:
df['age'].loc[df['sex'] == 'Male'].mean()

39.43354749885268

In [40]:
df['education'].loc[df['education'] == 'Bachelors'].value_counts()

Bachelors    5355
Name: education, dtype: int64

In [10]:
df['education'].value_counts().sum()

32561

In [44]:
df['education'].loc[df['education'] == 'Bachelors'].value_counts() / df['education'].value_counts().sum()

Bachelors    0.164461
Name: education, dtype: float64

In [49]:
df['education'].loc[df['education'] == 'Bachelors'].count() / df['education'].count().sum()

0.16446055096587942

In [45]:
maskhi = df['education'].isin(['Bachelors', 'Doctorate', 'Masters'])
masklo = ~df['education'].isin(['Bachelors', 'Doctorate', 'Masters'])
df['salary'][masklo].count()


25070

In [46]:
df['salary'][maskhi].count()

7491

In [15]:
4335 / 20715

0.20926864590876176

In [16]:
df['salary'][maskhi].value_counts().sum()

7491

In [17]:
df['salary'][maskhi].value_counts().sum()

7491

In [18]:
df['salary'][maskhi].loc[df['salary'] == '>50K'].value_counts().divide(df['salary'][maskhi].value_counts().sum()) 

>50K    0.465358
Name: salary, dtype: float64

In [19]:
df['salary'][maskhi].loc[df['salary'] == '>50K'].count() / df['salary'][maskhi].count().sum()

0.46535843011613937

In [20]:
df['salary'][masklo].loc[df['salary'] == '>50K'].value_counts().divide(df['salary'][masklo].value_counts().sum()) 

>50K    0.173714
Name: salary, dtype: float64

In [21]:
df['salary'][masklo].loc[df['salary'] == '>50K'].count() / df['salary'][masklo].count().sum()

0.173713601914639

In [22]:
df['hours-per-week'].min()

1

In [23]:
# maskminhour = df[['hours-per-week'] == df['hours-per-week'].min()]
# maskminhour
maskminhour = df['hours-per-week'] == df['hours-per-week'].min()


In [24]:
df[['hours-per-week']][maskminhour].count() 

hours-per-week    20
dtype: int64

In [25]:
df['salary'][maskminhour].loc[df['salary'] == '>50K'].count()

2

In [26]:
df['salary'][maskminhour].count()

20

In [27]:
df['salary'][maskminhour].loc[df['salary'] == '>50K'].count() / df['salary'][maskminhour].count()

0.1

In [28]:
df.groupby(['native-country']).count().head()

age  workclass  fnlwgt  education  education-num  \
native-country                                                     
?               583        583     583        583            583   
Cambodia         19         19      19         19             19   
Canada          121        121     121        121            121   
China            75         75      75         75             75   
Columbia         59         59      59         59             59   

                marital-status  occupation  relationship  race  sex  \
native-country                                                        
?                          583         583           583   583  583   
Cambodia                    19          19            19    19   19   
Canada                     121         121           121   121  121   
China                       75          75            75    75   75   
Columbia                    59          59            59    59   59   

                capital-gain  capital-loss  hours-per-week  salary  
native-country                                                      
?                        583           583             583     583  
Cambodia                  19            19              19      19  
Canada                   121           121             121     121  
China                     75            75              75      75  
Columbia                  59            59              59      59

In [29]:
df.loc[df['native-country'] == '?'].head()

age workclass  fnlwgt     education  education-num         marital-status  \
14   40   Private  121772     Assoc-voc             11     Married-civ-spouse   
38   31   Private   84154  Some-college             10     Married-civ-spouse   
51   18   Private  226956       HS-grad              9          Never-married   
61   32         ?  293936       7th-8th              4  Married-spouse-absent   
93   30   Private  117747       HS-grad              9     Married-civ-spouse   

       occupation   relationship                race     sex  capital-gain  \
14   Craft-repair        Husband  Asian-Pac-Islander    Male             0   
38          Sales        Husband               White    Male             0   
51  Other-service      Own-child               White  Female             0   
61              ?  Not-in-family               White    Male             0   
93          Sales           Wife  Asian-Pac-Islander  Female             0   

    capital-loss  hours-per-week native-country salary  
14             0              40              ?   >50K  
38             0              38              ?   >50K  
51             0              30              ?  <=50K  
61             0              40              ?  <=50K  
93          1573              35              ?  <=50K

In [30]:
df.loc[df['salary'] == '>50K'].groupby(['native-country']).count().sort_values('salary', ascending=False)

age  workclass  fnlwgt  education  education-num  \
native-country                                                          
United-States       7171       7171    7171       7171           7171   
?                    146        146     146        146            146   
Philippines           61         61      61         61             61   
Germany               44         44      44         44             44   
India                 40         40      40         40             40   
Canada                39         39      39         39             39   
Mexico                33         33      33         33             33   
England               30         30      30         30             30   
Italy                 25         25      25         25             25   
Cuba                  25         25      25         25             25   
Japan                 24         24      24         24             24   
China                 20         20      20         20             20   
Taiwan                20         20      20         20             20   
Iran                  18         18      18         18             18   
South                 16         16      16         16             16   
Poland                12         12      12         12             12   
France                12         12      12         12             12   
Puerto-Rico           12         12      12         12             12   
Jamaica               10         10      10         10             10   
El-Salvador            9          9       9          9              9   
Greece                 8          8       8          8              8   
Cambodia               7          7       7          7              7   
Yugoslavia             6          6       6          6              6   
Hong                   6          6       6          6              6   
Ireland                5          5       5          5              5   
Vietnam                5          5       5          5              5   
Ecuador                4          4       4          4              4   
Haiti                  4          4       4          4              4   
Portugal               4          4       4          4              4   
Scotland               3          3       3          3              3   
Thailand               3          3       3          3              3   
Hungary                3          3       3          3              3   
Guatemala              3          3       3          3              3   
Laos                   2          2       2          2              2   
Dominican-Republic     2          2       2          2              2   
Peru                   2          2       2          2              2   
Trinadad&Tobago        2          2       2          2              2   
Columbia               2          2       2          2              2   
Nicaragua              2          2       2          2              2   
Honduras               1          1       1          1              1   

                    marital-status  occupation  relationship  race   sex  \
native-country                                                             
United-States                 7171        7171          7171  7171  7171   
?                              146         146           146   146   146   
Philippines                     61          61            61    61    61   
Germany                         44          44            44    44    44   
India                           40          40            40    40    40   
Canada                          39          39            39    39    39   
Mexico                          33          33            33    33    33   
England                         30          30            30    30    30   
Italy                           25          25            25    25    25   
Cuba                            25          25            25    25    25   
Japan                           24        

In [31]:
df.loc[df['salary'] == '>50K'].groupby(['native-country']).count()

age  workclass  fnlwgt  education  education-num  \
native-country                                                          
?                    146        146     146        146            146   
Cambodia               7          7       7          7              7   
Canada                39         39      39         39             39   
China                 20         20      20         20             20   
Columbia               2          2       2          2              2   
Cuba                  25         25      25         25             25   
Dominican-Republic     2          2       2          2              2   
Ecuador                4          4       4          4              4   
El-Salvador            9          9       9          9              9   
England               30         30      30         30             30   
France                12         12      12         12             12   
Germany               44         44      44         44             44   
Greece                 8          8       8          8              8   
Guatemala              3          3       3          3              3   
Haiti                  4          4       4          4              4   
Honduras               1          1       1          1              1   
Hong                   6          6       6          6              6   
Hungary                3          3       3          3              3   
India                 40         40      40         40             40   
Iran                  18         18      18         18             18   
Ireland                5          5       5          5              5   
Italy                 25         25      25         25             25   
Jamaica               10         10      10         10             10   
Japan                 24         24      24         24             24   
Laos                   2          2       2          2              2   
Mexico                33         33      33         33             33   
Nicaragua              2          2       2          2              2   
Peru                   2          2       2          2              2   
Philippines           61         61      61         61             61   
Poland                12         12      12         12             12   
Portugal               4          4       4          4              4   
Puerto-Rico           12         12      12         12             12   
Scotland               3          3       3          3              3   
South                 16         16      16         16             16   
Taiwan                20         20      20         20             20   
Thailand               3          3       3          3              3   
Trinadad&Tobago        2          2       2          2              2   
United-States       7171       7171    7171       7171           7171   
Vietnam                5          5       5          5              5   
Yugoslavia             6          6       6          6              6   

                    marital-status  occupation  relationship  race   sex  \
native-country                                                             
?                              146         146           146   146   146   
Cambodia                         7           7             7     7     7   
Canada                          39          39            39    39    39   
China                           20          20            20    20    20   
Columbia                         2           2             2     2     2   
Cuba                            25          25            25    25    25   
Dominican-Republic               2           2             2     2     2   
Ecuador                          4           4             4     4     4   
El-Salvador                      9           9             9     9     9   
England                         30          30            30    30    30   
France                          12        

In [32]:
maskgroup = df.loc[df['salary'] == '>50K'].groupby(['native-country']).count()
maskgroup.loc[maskgroup['age'] == maskgroup['age'].max()]['age']

native-country
United-States    7171
Name: age, dtype: int64

In [98]:
# Correct version
maskrichhi = df.loc[df['salary'] == '>50K'].groupby(['native-country']).count()['age']
maskgroupall = df.groupby(['native-country']).count()['age']
earn_rich_percent_country = maskrichhi / maskgroupall
print(earn_rich_percent_country.idxmax(), ':', earn_rich_percent_country.max())


Iran : 0.4186046511627907


In [36]:
top_ocup = df.loc[(df['salary'] == '>50K') & (df['native-country'] == 'India')].groupby(['occupation']).count().idxmax()[0]
top_ocup

age  workclass  fnlwgt  education  education-num  \
occupation                                                           
Adm-clerical        1          1       1          1              1   
Exec-managerial     8          8       8          8              8   
Other-service       2          2       2          2              2   
Prof-specialty     25         25      25         25             25   
Sales               1          1       1          1              1   
Tech-support        2          2       2          2              2   
Transport-moving    1          1       1          1              1   

                  marital-status  relationship  race  sex  capital-gain  \
occupation                                                                
Adm-clerical                   1             1     1    1             1   
Exec-managerial                8             8     8    8             8   
Other-service                  2             2     2    2             2   
Prof-specialty                25            25    25   25            25   
Sales                          1             1     1    1             1   
Tech-support                   2             2     2    2             2   
Transport-moving               1             1     1    1             1   

                  capital-loss  hours-per-week  native-country  salary  
occupation                                                              
Adm-clerical                 1               1               1       1  
Exec-managerial              8               8               8       8  
Other-service                2               2               2       2  
Prof-specialty              25              25              25      25  
Sales                        1               1               1       1  
Tech-support                 2               2               2       2  
Transport-moving             1               1               1       1


# Exmaple of Masking
import pandas as pd

values = [1, 2, 3, 4]
series = pd.Series([0, 1, 2, 3, 4, 5])

mask = series.isin(values)
result = series[mask]

print(result)


import pandas as pd

df = pd.DataFrame({'item': ['apple', 'banana', 'cherry', 'date'],'price': [1, 2, 3, 4]})

max_index = df['price'].idxmax()
print(max_index)
