In [2]:
import numpy as np
import pandas as pd

In [3]:
value = [1, 2, 3, 4, 5, 6, 7, 8,10]


In [4]:
grid = np.array([[value[0], value[1], value[2]], [value[3], value[4], value[5]], [value[6],value[7],value[8]]])
print(grid)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]


Best way of doing this: 


In [5]:
grid = np.array(value).reshape((3,3))
print(grid)

print(np.mean(grid, axis =1))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]
[2.         5.         8.33333333]


In [6]:
df = pd.read_csv('./Demographic-Data-Analyzer/adult.data.csv')
df.head()

age         workclass  fnlwgt  education  education-num  \
0   39         State-gov   77516  Bachelors             13   
1   50  Self-emp-not-inc   83311  Bachelors             13   
2   38           Private  215646    HS-grad              9   
3   53           Private  234721       11th              7   
4   28           Private  338409  Bachelors             13   

       marital-status         occupation   relationship   race     sex  \
0       Never-married       Adm-clerical  Not-in-family  White    Male   
1  Married-civ-spouse    Exec-managerial        Husband  White    Male   
2            Divorced  Handlers-cleaners  Not-in-family  White    Male   
3  Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4  Married-civ-spouse     Prof-specialty           Wife  Black  Female   

   capital-gain  capital-loss  hours-per-week native-country salary  
0          2174             0              40  United-States  <=50K  
1             0             0              13  United-States  <=50K  
2             0             0              40  United-States  <=50K  
3             0             0              40  United-States  <=50K  
4             0             0              40           Cuba  <=50K

In [114]:
race_count = pd.Series(df['race'].value_counts())
race_count

White                 27816
Black                  3124
Asian-Pac-Islander     1039
Amer-Indian-Eskimo      311
Other                   271
Name: race, dtype: int64

In [38]:
df['age'].loc[df['sex'] == 'Male'].mean()

39.43354749885268

In [42]:
df['education'].loc[df['education'] == 'Bachelors'].value_counts()

Bachelors    5355
Name: education, dtype: int64

In [43]:
df['education'].value_counts().sum()

32561

In [46]:
df['education'].loc[df['education'] == 'Bachelors'].value_counts() / df['education'].value_counts().sum()

Bachelors    0.164461
Name: education, dtype: float64

In [49]:
df['education'].loc[df['education'] == 'Bachelors'].value_counts().divide(df['education'].value_counts().sum())

Bachelors    0.164461
Name: education, dtype: float64

In [135]:
maskhi = df['education'].isin(['Bachelors', 'Doctorate', 'Masters'])
masklo = ~df['education'].isin(['Bachelors', 'Doctorate', 'Masters'])
df['salary'][masklo].count()


25070

In [136]:
df['salary'][maskhi].count()

7491

In [124]:
4335 / 20715

0.20926864590876176

In [110]:
df['salary'][maskhi].value_counts().sum()

7491

In [130]:
df['salary'][maskhi].value_counts().sum()

7491

In [ ]:
df['salary'][maskhi].loc[df['salary'] == '>50K'].value_counts().divide(df['salary'][maskhi].value_counts().sum()) 

>50K    0.465358
Name: salary, dtype: float64

In [133]:
df['salary'][maskhi].loc[df['salary'] == '>50K'].count() / df['salary'][maskhi].count().sum()

0.46535843011613937

In [128]:
df['salary'][masklo].loc[df['salary'] == '>50K'].value_counts().divide(df['salary'][masklo].value_counts().sum()) 

>50K    0.173714
Name: salary, dtype: float64

In [134]:
df['salary'][masklo].loc[df['salary'] == '>50K'].count() / df['salary'][masklo].count().sum()

0.173713601914639

In [66]:
# Exmaple of Masking
import pandas as pd

values = [1, 2, 3, 4]
series = pd.Series([0, 1, 2, 3, 4, 5])

mask = series.isin(values)
result = series[mask]

print(result)


1    1
2    2
3    3
4    4
dtype: int64
