In [1]:
import numpy as np

In [3]:
value = [1, 2, 3, 4, 5, 6, 7, 8,10]


In [ ]:
grid = np.array([[value[0], value[1], value[2]], [value[3], value[4], value[5]], [value[6],value[7],value[8]]])
print(grid)

Best way of doing this: 


In [9]:
grid = np.array(value).reshape((3,3))
print(grid)

print(np.mean(grid, axis =1))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]
[2.         5.         8.33333333]
